// src/webview/judge/Testcase.tsx
import { observer, useObservable } from "@legendapp/state/react";
import type { Observable } from "@legendapp/state";
import * as v from "valibot";

import { TestcaseSchema } from "~shared/schemas";
import { Status, Stdio } from "~shared/enums";
import AutoresizeTextarea from "../AutoresizeTextarea";
import { useCallback } from "react";
import { Action, ProviderMessageType } from "~shared/judge-messages";
import { postProviderMessage } from "./message";
import { getStatusColor } from "~webview/utils";

type ITestcase = v.InferOutput<typeof TestcaseSchema>;

interface Props {
  id: number;
  testcase$: Observable<ITestcase>;
}

const Testcase = observer(function Testcase({ id, testcase$ }: Props) {
  const newStdin$ = useObservable("");

  const handleSave = useCallback(() => {
    const stdin = testcase$.stdin.get();
    const acceptedStdout = testcase$.acceptedStdout.get();
    // the extension host will send back shortened version of both of these
    testcase$.stdin.set("");
    testcase$.acceptedStdout.set("");
    postProviderMessage({
      type: ProviderMessageType.SAVE,
      id,
      stdin,
      acceptedStdout,
    });
  }, [testcase$, id]);

  const handleExpandStdio = useCallback(
    (stdio: Stdio) => postProviderMessage({ type: ProviderMessageType.VIEW, id, stdio }),
    [id]
  );

  const handleNewStdinKeyUp = useCallback(
    (event: React.KeyboardEvent) => {
      if (event.key === "Enter") {
        postProviderMessage({
          type: ProviderMessageType.STDIN,
          id,
          data: newStdin$.peek(),
        });
        newStdin$.set("");
      }
    },
    [id, newStdin$]
  );

  const handleAction = useCallback(
    (action: Action) => {
      postProviderMessage({ type: ProviderMessageType.ACTION, id, action });
    },
    [id]
  );

  const handleRun = useCallback(() => {
    newStdin$.set("");
    handleAction(Action.RUN);
  }, [handleAction, newStdin$]);

  const handleEdit = useCallback(() => handleAction(Action.EDIT), [handleAction]);
  const handleDelete = useCallback(() => handleAction(Action.DELETE), [handleAction]);
  const handleAccept = useCallback(() => handleAction(Action.ACCEPT), [handleAction]);
  const handleDecline = useCallback(() => handleAction(Action.DECLINE), [handleAction]);
  const handleToggleVisibility = useCallback(
    () => handleAction(Action.TOGGLE_VISIBILITY),
    [handleAction]
  );
  const handleToggleSkip = useCallback(() => handleAction(Action.TOGGLE_SKIP), [handleAction]);
  const handleStop = useCallback(() => handleAction(Action.STOP), [handleAction]);
  const handleCompare = useCallback(() => handleAction(Action.COMPARE), [handleAction]);

  const status = testcase$.status.get();
  const visible = testcase$.shown.get();
  const skipped = testcase$.skipped.get();
  const toggled = testcase$.toggled.get();

  const statusColor = getStatusColor(status);

  switch (status) {
    case Status.CE:
      return (
        <div className="testcase-container">
          <div className={`testcase-toolbar ${skipped ? "testcase-toolbar--hidden" : ""}`}>
            <div className="testcase-toolbar-left">
              <strong className="testcase-elapsed" style={{ backgroundColor: statusColor }}>
                CE
              </strong>
              <div className="testcase-toolbar-icon" onClick={handleRun}>
                <div className="codicon codicon-run-below"></div>
              </div>
              <div className="testcase-toolbar-icon" onClick={handleEdit}>
                <div className="codicon codicon-edit"></div>
              </div>
              <div className="testcase-toolbar-icon" onClick={handleDelete}>
                <div className="codicon codicon-trash"></div>
              </div>
              <div className="testcase-toolbar-icon" onClick={handleToggleVisibility}>
                <div className={`codicon ${visible ? "codicon-eye-closed" : "codicon-eye"}`}></div>
              </div>
              <div
                className="testcase-toolbar-icon  testcase-toolbar-icon--visibility"
                onClick={handleToggleSkip}
              >
                <div
                  className={`codicon ${skipped ? "codicon-debug-connected" : "codicon-debug-disconnect"}`}
                ></div>
              </div>
            </div>
          </div>
        </div>
      );
    case Status.NA:
    case Status.AC:
    case Status.WA:
    case Status.RE:
    case Status.TL:
      return (
        <div className="testcase-container">
          <div className={`testcase-toolbar ${skipped ? "testcase-toolbar--hidden" : ""}`}>
            <div className="testcase-toolbar-left">
              <strong className="testcase-elapsed" style={{ backgroundColor: statusColor }}>
                {testcase$.elapsed.get()}ms
              </strong>
              <div className="testcase-toolbar-icon" onClick={handleRun}>
                <div className="codicon codicon-run-below"></div>
              </div>
              <div className="testcase-toolbar-icon" onClick={handleEdit}>
                <div className="codicon codicon-edit"></div>
              </div>
              <div className="testcase-toolbar-icon" onClick={handleDelete}>
                <div className="codicon codicon-trash"></div>
              </div>
              <div className="testcase-toolbar-icon" onClick={handleToggleVisibility}>
                <div className={`codicon ${visible ? "codicon-eye-closed" : "codicon-eye"}`}></div>
              </div>
              <div
                className="testcase-toolbar-icon  testcase-toolbar-icon--visibility"
                onClick={handleToggleSkip}
              >
                <div
                  className={`codicon ${skipped ? "codicon-debug-connected" : "codicon-debug-disconnect"}`}
                ></div>
              </div>
            </div>
            <div className="testcase-toolbar-right">
              {(status === Status.NA || status === Status.WA) && (
                <div className="testcase-toolbar-icon" onClick={handleAccept}>
                  <div className="codicon codicon-pass"></div>
                </div>
              )}
              {status === Status.AC && (
                <div className="testcase-toolbar-icon" onClick={handleDecline}>
                  <div className="codicon codicon-close"></div>
                </div>
              )}
              {status == Status.WA && (
                <div className="testcase-toolbar-icon" onClick={handleCompare}>
                  <div className="codicon codicon-diff-single"></div>
                </div>
              )}
            </div>
          </div>
          {!skipped && visible && !(status === Status.AC && !toggled) && (
            <>
              <AutoresizeTextarea
                input$={testcase$.stdin}
                readonly
                hiddenOnEmpty
                placeholder="Stdin..."
                onExpand={() => handleExpandStdio(Stdio.STDIN)}
              />
              <AutoresizeTextarea
                input$={testcase$.stderr}
                readonly
                hiddenOnEmpty
                placeholder="Stderr..."
                variant="stderr"
                onExpand={() => handleExpandStdio(Stdio.STDERR)}
              />
              <AutoresizeTextarea
                input$={testcase$.stdout}
                readonly
                hiddenOnEmpty
                placeholder="Stdout..."
                onExpand={() => handleExpandStdio(Stdio.STDOUT)}
              />
              {status === Status.WA && (
                <AutoresizeTextarea
                  input$={testcase$.acceptedStdout}
                  readonly
                  hiddenOnEmpty
                  placeholder="Accepted stdout..."
                  variant="accepted"
                  onExpand={() => handleExpandStdio(Stdio.ACCEPTED_STDOUT)}
                />
              )}
            </>
          )}
        </div>
      );
    case Status.COMPILING:
      return (
        <div className="testcase-container">
          <div className="testcase-toolbar">
            <div className="testcase-toolbar-left">
              <strong
                className="testcase-elapsed"
                style={{ backgroundColor: getStatusColor(status) }}
              >
                COMPILING
              </strong>
              <div className="testcase-toolbar-icon testcase-toolbar-icon-exclude-highlight">
                <div className="codicon codicon-loading codicon-modifier-spin"></div>
              </div>
            </div>
          </div>
        </div>
      );
    case Status.RUNNING:
      return (
        <div className="testcase-container">
          <div className="testcase-toolbar">
            <div className="testcase-toolbar-left">
              <div className="testcase-toolbar-icon testcase-toolbar-icon-exclude-highlight">
                <div className="codicon codicon-loading codicon-modifier-spin"></div>
              </div>
              <div className="testcase-toolbar-icon" onClick={handleStop}>
                <div className="codicon codicon-stop-circle"></div>
              </div>
            </div>
          </div>
          {visible && (
            <>
              <AutoresizeTextarea
                input$={testcase$.stdin}
                readonly
                hiddenOnEmpty
                placeholder="Stdin..."
                onExpand={() => handleExpandStdio(Stdio.STDIN)}
              />
              <AutoresizeTextarea
                input$={newStdin$}
                placeholder="New stdin..."
                onKeyUp={handleNewStdinKeyUp}
                variant="active"
              />
              <AutoresizeTextarea
                input$={testcase$.stderr}
                readonly
                hiddenOnEmpty
                placeholder="Stderr..."
                variant="stderr"
                onExpand={() => handleExpandStdio(Stdio.STDERR)}
              />
              <AutoresizeTextarea input$={testcase$.stdout} readonly placeholder="Stdout..." />
            </>
          )}
        </div>
      );
    case Status.EDITING:
      return (
        <div className="testcase-container">
          <div className="testcase-toolbar">
            <div className="testcase-toolbar-left">
              <div className="testcase-toolbar-icon testcase-toolbar-icon-exclude-highlight">
                <div className="codicon codicon-sync codicon-modifier-spin"></div>
              </div>
              <div className="testcase-toolbar-icon">
                <div className="codicon codicon-save" onClick={handleSave}></div>
              </div>
            </div>
          </div>
          <AutoresizeTextarea
            input$={testcase$.stdin}
            placeholder="Stdin..."
            onExpand={() => handleExpandStdio(Stdio.STDIN)}
          />
          <AutoresizeTextarea
            input$={testcase$.acceptedStdout}
            placeholder="Accepted stdout..."
            variant="accepted"
            onExpand={() => handleExpandStdio(Stdio.ACCEPTED_STDOUT)}
          />
        </div>
      );
    default:
      return <></>;
  }
});

export default Testcase;

// src/webview/judge/Testcase.svelte
<script lang="ts">
  import type * as v from "valibot";

  import type { TestcaseSchema } from "~shared/schemas";
  import { Status, Stdio } from "~shared/enums";
  import AutoresizeTextarea from "../AutoresizeTextarea.svelte";
  import { Action, ProviderMessageType } from "~shared/judge-messages";
  import { postProviderMessage } from "./message";

  type ITestcase = v.InferOutput<typeof TestcaseSchema>;

  interface Props {
    id: number;
    testcase: ITestcase;
    updateTestcaseData: (id: number, updates: Partial<ITestcase>) => void;
  }

  let { id, testcase, updateTestcaseData }: Props = $props();

  let newStdin = $state("");

  function handleSave() {
    const stdin = testcase.stdin;
    const acceptedStdout = testcase.acceptedStdout;
    // Clear the values locally (extension will send back shortened version)
    updateTestcaseData(id, { stdin: "", acceptedStdout: "" });
    postProviderMessage({
      type: ProviderMessageType.SAVE,
      id,
      stdin,
      acceptedStdout,
    });
  }

  function handleExpandStdio(stdio: Stdio) {
    postProviderMessage({ type: ProviderMessageType.VIEW, id, stdio });
  }

  function handleNewStdinKeyUp(event: KeyboardEvent) {
    if (event.key === "Enter") {
      postProviderMessage({
        type: ProviderMessageType.STDIN,
        id,
        data: newStdin,
      });
      newStdin = "";
    }
  }

  function handleAction(action: Action) {
    postProviderMessage({ type: ProviderMessageType.ACTION, id, action });
  }

  function handleRun() {
    newStdin = "";
    handleAction(Action.RUN);
  }

  function handleEdit() {
    handleAction(Action.EDIT);
  }

  function handleDelete() {
    handleAction(Action.DELETE);
  }

  function handleAccept() {
    handleAction(Action.ACCEPT);
  }

  function handleDecline() {
    handleAction(Action.DECLINE);
  }

  function handleToggleVisibility() {
    handleAction(Action.TOGGLE_VISIBILITY);
  }

  function handleToggleSkip() {
    handleAction(Action.TOGGLE_SKIP);
  }

  function handleStop() {
    handleAction(Action.STOP);
  }

  function handleCompare() {
    handleAction(Action.COMPARE);
  }

  // Update testcase fields when child component changes them
  function handleStdinChange(value: string) {
    updateTestcaseData(id, { stdin: value });
  }

  function handleAcceptedStdoutChange(value: string) {
    updateTestcaseData(id, { acceptedStdout: value });
  }

  function handleNewStdinChange(value: string) {
    newStdin = value;
  }

  // Derived values
  const status = $derived(testcase.status);
  const visible = $derived(testcase.shown);
  const skipped = $derived(testcase.skipped);
  const toggled = $derived(testcase.toggled);
</script>

{#if status === Status.CE}
  <div class="testcase-container">
    <div class="testcase-toolbar" class:testcase-toolbar--hidden={skipped}>
      <div class="testcase-toolbar-left">
        <strong class="testcase-elapsed" data-status={status}>CE</strong>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div class="testcase-toolbar-icon" onclick={handleRun}>
          <div class="codicon codicon-run-below"></div>
        </div>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div class="testcase-toolbar-icon" onclick={handleEdit}>
          <div class="codicon codicon-edit"></div>
        </div>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div class="testcase-toolbar-icon" onclick={handleDelete}>
          <div class="codicon codicon-trash"></div>
        </div>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div class="testcase-toolbar-icon" onclick={handleToggleVisibility}>
          <div class="codicon {visible ? 'codicon-eye-closed' : 'codicon-eye'}"></div>
        </div>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div
          class="testcase-toolbar-icon testcase-toolbar-icon--visibility"
          onclick={handleToggleSkip}
        >
          <div
            class="codicon {skipped ? 'codicon-debug-connected' : 'codicon-debug-disconnect'}"
          ></div>
        </div>
      </div>
    </div>
  </div>
{:else if status === Status.NA || status === Status.AC || status === Status.WA || status === Status.RE || status === Status.TL}
  <div class="testcase-container">
    <div class="testcase-toolbar" class:testcase-toolbar--hidden={skipped}>
      <div class="testcase-toolbar-left">
        <strong class="testcase-elapsed" data-status={status}>
          {testcase.elapsed}ms
        </strong>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div class="testcase-toolbar-icon" onclick={handleRun}>
          <div class="codicon codicon-run-below"></div>
        </div>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div class="testcase-toolbar-icon" onclick={handleEdit}>
          <div class="codicon codicon-edit"></div>
        </div>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div class="testcase-toolbar-icon" onclick={handleDelete}>
          <div class="codicon codicon-trash"></div>
        </div>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div class="testcase-toolbar-icon" onclick={handleToggleVisibility}>
          <div class="codicon {visible ? 'codicon-eye-closed' : 'codicon-eye'}"></div>
        </div>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div
          class="testcase-toolbar-icon testcase-toolbar-icon--visibility"
          onclick={handleToggleSkip}
        >
          <div
            class="codicon {skipped ? 'codicon-debug-connected' : 'codicon-debug-disconnect'}"
          ></div>
        </div>
      </div>
      <div class="testcase-toolbar-right">
        {#if status === Status.NA || status === Status.WA}
          <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
          <div class="testcase-toolbar-icon" onclick={handleAccept}>
            <div class="codicon codicon-pass"></div>
          </div>
        {/if}
        {#if status === Status.AC}
          <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
          <div class="testcase-toolbar-icon" onclick={handleDecline}>
            <div class="codicon codicon-close"></div>
          </div>
        {/if}
        {#if status === Status.WA}
          <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
          <div class="testcase-toolbar-icon" onclick={handleCompare}>
            <div class="codicon codicon-diff-single"></div>
          </div>
        {/if}
      </div>
    </div>
    {#if !skipped && visible && !(status === Status.AC && !toggled)}
      <AutoresizeTextarea
        value={testcase.stdin}
        readonly
        hiddenOnEmpty
        placeholder="Stdin..."
        onexpand={() => handleExpandStdio(Stdio.STDIN)}
      />
      <AutoresizeTextarea
        value={testcase.stderr}
        readonly
        hiddenOnEmpty
        placeholder="Stderr..."
        variant="stderr"
        onexpand={() => handleExpandStdio(Stdio.STDERR)}
      />
      <AutoresizeTextarea
        value={testcase.stdout}
        readonly
        hiddenOnEmpty
        placeholder="Stdout..."
        onexpand={() => handleExpandStdio(Stdio.STDOUT)}
      />
      {#if status === Status.WA}
        <AutoresizeTextarea
          value={testcase.acceptedStdout}
          readonly
          hiddenOnEmpty
          placeholder="Accepted stdout..."
          variant="accepted"
          onexpand={() => handleExpandStdio(Stdio.ACCEPTED_STDOUT)}
        />
      {/if}
    {/if}
  </div>
{:else if status === Status.COMPILING}
  <div class="testcase-container">
    <div class="testcase-toolbar">
      <div class="testcase-toolbar-left">
        <strong class="testcase-elapsed" data-status={status}> COMPILING </strong>
        <div class="testcase-toolbar-icon testcase-toolbar-icon-exclude-highlight">
          <div class="codicon codicon-loading codicon-modifier-spin"></div>
        </div>
      </div>
    </div>
  </div>
{:else if status === Status.RUNNING}
  <div class="testcase-container">
    <div class="testcase-toolbar">
      <div class="testcase-toolbar-left">
        <div class="testcase-toolbar-icon testcase-toolbar-icon-exclude-highlight">
          <div class="codicon codicon-loading codicon-modifier-spin"></div>
        </div>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div class="testcase-toolbar-icon" onclick={handleStop}>
          <div class="codicon codicon-stop-circle"></div>
        </div>
      </div>
    </div>
    {#if visible}
      <AutoresizeTextarea
        value={testcase.stdin}
        readonly
        hiddenOnEmpty
        placeholder="Stdin..."
        onexpand={() => handleExpandStdio(Stdio.STDIN)}
      />
      <AutoresizeTextarea
        value={newStdin}
        placeholder="New stdin..."
        onkeyup={handleNewStdinKeyUp}
        onchange={handleNewStdinChange}
        variant="active"
      />
      <AutoresizeTextarea
        value={testcase.stderr}
        readonly
        hiddenOnEmpty
        placeholder="Stderr..."
        variant="stderr"
        onexpand={() => handleExpandStdio(Stdio.STDERR)}
      />
      <AutoresizeTextarea value={testcase.stdout} readonly placeholder="Stdout..." />
    {/if}
  </div>
{:else if status === Status.EDITING}
  <div class="testcase-container">
    <div class="testcase-toolbar">
      <div class="testcase-toolbar-left">
        <div class="testcase-toolbar-icon testcase-toolbar-icon-exclude-highlight">
          <div class="codicon codicon-sync codicon-modifier-spin"></div>
        </div>
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
        <div class="testcase-toolbar-icon" onclick={handleSave}>
          <div class="codicon codicon-save"></div>
        </div>
      </div>
    </div>
    <AutoresizeTextarea
      value={testcase.stdin}
      placeholder="Stdin..."
      onchange={handleStdinChange}
      onexpand={() => handleExpandStdio(Stdio.STDIN)}
    />
    <AutoresizeTextarea
      value={testcase.acceptedStdout}
      placeholder="Accepted stdout..."
      variant="accepted"
      onchange={handleAcceptedStdoutChange}
      onexpand={() => handleExpandStdio(Stdio.ACCEPTED_STDOUT)}
    />
  </div>
{/if}

<style>
  .testcase-toolbar {
    display: flex;
    align-items: center;
    margin-bottom: 6px;
  }

  .testcase-toolbar--hidden > :global(*) > :global(*:not(.testcase-toolbar-icon--visibility)) {
    opacity: 0.5;
  }

  .testcase-toolbar-left {
    display: flex;
    align-items: center;
    justify-content: flex-start;
    gap: 6px;
  }

  .testcase-toolbar-right {
    display: flex;
    align-items: center;
    margin-left: auto;
    justify-content: flex-end;
    gap: 6px;
  }

  .testcase-toolbar-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    align-self: stretch;
    border-radius: 2px;
    padding: 3px;
  }

  .testcase-toolbar-icon:not(.testcase-toolbar-icon-exclude-highlight):hover {
    background: var(--vscode-button-secondaryBackground);
  }

  .testcase-container {
    margin-bottom: 24px;
  }

  .testcase-elapsed {
    display: flex;
    align-items: center;
    height: 22px;
    padding: 1px 6px;
    border-radius: 11px;
    font-size: 15px;
    font-weight: bold;
    line-height: 1;
    background-color: var(--vscode-button-secondaryBackground);
  }

  /* Status-specific colors using data-status attribute */
  /* CE=0 */
  .testcase-elapsed[data-status="0"] {
    background-color: var(--vscode-terminal-ansiMagenta);
  }

  /* RE=1 */
  .testcase-elapsed[data-status="1"] {
    background-color: var(--vscode-terminal-ansiRed);
  }

  /* WA=2 */
  .testcase-elapsed[data-status="2"] {
    background-color: var(--vscode-terminal-ansiYellow);
  }

  /* AC=3 */
  .testcase-elapsed[data-status="3"] {
    background-color: var(--vscode-terminal-ansiGreen);
  }

  /* TL=5 */
  .testcase-elapsed[data-status="5"] {
    background-color: var(--vscode-terminal-ansiRed);
  }
</style>
