// src/webview/stress/App.tsx
import { observable } from "@legendapp/state";
import { observer } from "@legendapp/state/react";
import { useCallback, useEffect } from "react";
import * as v from "valibot";

import { Status } from "~shared/enums";
import {
  ProviderMessageType,
  RunningMessageSchema,
  ShowMessageSchema,
  StatusMessageSchema,
  StdioMessageSchema,
  WebviewMessage,
  WebviewMessageType,
} from "~shared/stress-messages";
import { postProviderMessage } from "./message";
import State, { IState } from "./State";

type IShowMessage = v.InferOutput<typeof ShowMessageSchema>;
type IStdioMessage = v.InferOutput<typeof StdioMessageSchema>;

const state$ = observable({
  items: [
    { data: "", status: Status.NA },
    { data: "", status: Status.NA },
    { data: "", status: Status.NA },
  ] as IState[],
  showView: true,
  running: false,
});

const expand = (id: number) => postProviderMessage({ type: ProviderMessageType.VIEW, id });
const add = (id: number) => postProviderMessage({ type: ProviderMessageType.ADD, id });

window.addEventListener("message", (event: MessageEvent<WebviewMessage>) => {
  switch (event.data.type) {
    case WebviewMessageType.STATUS:
      handleStatus(event.data);
      break;
    case WebviewMessageType.STDIO:
      handleStdio(event.data);
      break;
    case WebviewMessageType.CLEAR:
      handleClear();
      break;
    case WebviewMessageType.SHOW:
      handleShow(event.data);
      break;
    case WebviewMessageType.RUNNING:
      handleRunning(event.data);
      break;
  }
});

function handleStatus({ id, status }: v.InferOutput<typeof StatusMessageSchema>) {
  state$.items[id].status.set(status);
}

function handleStdio({ id, data }: IStdioMessage) {
  state$.items[id].data.set((prev) => prev + data);
}

function handleClear() {
  for (let i = 0; i < 3; i++) {
    state$.items[i].data.set("");
    state$.items[i].status.set(Status.NA);
  }
}

function handleShow({ visible }: IShowMessage) {
  state$.showView.set(visible);
}

function handleRunning({ value }: v.InferOutput<typeof RunningMessageSchema>) {
  state$.running.set(value);
}

const App = observer(function App() {
  const show = state$.showView.get();

  const handleExpand = useCallback((id: number) => expand(id), []);
  const handleAdd = useCallback((id: number) => add(id), []);

  useEffect(() => postProviderMessage({ type: ProviderMessageType.LOADED }), []);

  if (show) {
    return (
      <>
        {[0, 1, 2].map((id) => (
          <State
            key={id}
            id={id}
            state$={state$.items[id]}
            onView={handleExpand}
            onAdd={handleAdd}
          />
        ))}
      </>
    );
  }

  return (
    <div id="empty-state">
      <div className="codicon codicon-symbol-event" style={{ fontSize: 150 }}></div>
      <p>Open a file to get started</p>
    </div>
  );
});

export default App;

// src/webview/stress/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type * as v from "valibot";

  import { Status } from "~shared/enums";
  import {
    ProviderMessageType,
    type RunningMessageSchema,
    type ShowMessageSchema,
    type StatusMessageSchema,
    type StdioMessageSchema,
    type WebviewMessage,
    WebviewMessageType,
  } from "~shared/stress-messages";
  import { postProviderMessage } from "./message";
  import State from "./State.svelte";

  type IShowMessage = v.InferOutput<typeof ShowMessageSchema>;
  type IStdioMessage = v.InferOutput<typeof StdioMessageSchema>;

  interface IStateData {
    data: string;
    status: Status;
  }

  // Reactive state using Svelte 5 runes
  let items = $state<IStateData[]>([
    { data: "", status: Status.NA },
    { data: "", status: Status.NA },
    { data: "", status: Status.NA },
  ]);
  let showView = $state(true);
  let _running = $state(false);

  function expand(id: number) {
    postProviderMessage({ type: ProviderMessageType.VIEW, id });
  }

  function add(id: number) {
    postProviderMessage({ type: ProviderMessageType.ADD, id });
  }

  function handleStatus({ id, status }: v.InferOutput<typeof StatusMessageSchema>) {
    items[id].status = status;
  }

  function handleStdio({ id, data }: IStdioMessage) {
    items[id].data += data;
  }

  function handleClear() {
    for (let i = 0; i < 3; i++) {
      items[i].data = "";
      items[i].status = Status.NA;
    }
  }

  function handleShow({ visible }: IShowMessage) {
    showView = visible;
  }

  function handleRunning({ value }: v.InferOutput<typeof RunningMessageSchema>) {
    _running = value;
  }

  onMount(() => {
    const handleMessage = (event: MessageEvent<WebviewMessage>) => {
      switch (event.data.type) {
        case WebviewMessageType.STATUS:
          handleStatus(event.data);
          break;
        case WebviewMessageType.STDIO:
          handleStdio(event.data);
          break;
        case WebviewMessageType.CLEAR:
          handleClear();
          break;
        case WebviewMessageType.SHOW:
          handleShow(event.data);
          break;
        case WebviewMessageType.RUNNING:
          handleRunning(event.data);
          break;
      }
    };

    window.addEventListener("message", handleMessage);
    postProviderMessage({ type: ProviderMessageType.LOADED });

    return () => {
      window.removeEventListener("message", handleMessage);
    };
  });
</script>

{#if showView}
  {#each items as item, index (index)}
    <State id={index} state={item} onView={expand} onAdd={add} />
  {/each}
{:else}
  <div id="empty-state">
    <div class="codicon codicon-symbol-event empty-state-icon"></div>
    <p>Open a file to get started</p>
  </div>
{/if}

<style>
  #empty-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 8px;
    min-height: 100vh;
  }

  .empty-state-icon {
    font-size: 150px;
  }
</style>
